# 파일 호출 / 저장

In [46]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv('/content/drive/MyDrive/MLStudy/ch03_data_preprocessing/13_file_load_save_data/fruit.csv')

In [49]:
df.head(10)     # 처음부터 n행 출력, 기본값은 5행

   Unnamed: 0   품목 크기    금액    수수료
0           0  바나나  중  2000  200.0
1           1  바나나  대  3000  300.0
2           2  바나나  중  2000  200.0
3           3  토마토  대  1500  150.0
4           4  토마토  소   500   50.0
5           5   사과  중  3000  300.0
6           6  바나나  대  3000  300.0
7           7   사과  중  3000  300.0
8           8  토마토  대  1500  150.0
9           9  토마토  소   500   50.0

In [50]:
df.tail()     # 뒤에서부터 5행 출력

    Unnamed: 0   품목 크기    금액    수수료
51          51   사과  대  4000  400.0
52          52   사과  소  2000  200.0
53          53  토마토  대  1500  150.0
54          54   사과  소  2000  200.0
55          55  토마토  대  1500  150.0

첫 번째 열을 인덱스열로 삼고싶은 경우

In [51]:
df = pd.read_csv('/content/drive/MyDrive/MLStudy/ch03_data_preprocessing/13_file_load_save_data/fruit.csv', index_col=0)

In [52]:
df.head()

    품목 크기    금액    수수료
0  바나나  중  2000  200.0
1  바나나  대  3000  300.0
2  바나나  중  2000  200.0
3  토마토  대  1500  150.0
4  토마토  소   500   50.0

csv 파일이 아닌 경우

In [53]:
df = pd.read_csv('/content/drive/MyDrive/MLStudy/ch03_data_preprocessing/13_file_load_save_data/read_sep.txt', index_col=0, sep='|')

In [54]:
df.head()

       A   B   C
index
0      1  11  21
1      2  12  22
2      3  13  23

header가 여러 줄인 경우

In [55]:
df = pd.read_csv('/content/drive/MyDrive/MLStudy/ch03_data_preprocessing/13_file_load_save_data/multi_header.csv', header=1)

In [56]:
df

   a   b   c
0  1  11  21
1  2  12  22
2  3  13  23
3  4  14  24

In [57]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

데이터를 읽으면서 칼럼명을 추가하고 싶을 때

In [58]:
df = pd.read_csv('/content/drive/MyDrive/MLStudy/ch03_data_preprocessing/13_file_load_save_data/fruit_no_column.csv', index_col=0, names=['품목', '크기', '금액', '수수료'])
df.head()

    품목 크기    금액    수수료
0  바나나  중  2000  200.0
1  바나나  대  3000  300.0
2  바나나  중  2000  200.0
3  토마토  대  1500  150.0
4  토마토  소   500   50.0

원하는 칼럼만 쓰고 싶을 때

In [59]:
df = pd.read_csv('/content/drive/MyDrive/MLStudy/ch03_data_preprocessing/13_file_load_save_data/fruit.csv', usecols=['품목', '크기'])
df.head()

    품목 크기
0  바나나  중
1  바나나  대
2  바나나  중
3  토마토  대
4  토마토  소

파일 저장

In [60]:
df.to_csv('/content/drive/MyDrive/MLStudy/ch03_data_preprocessing/13_file_load_save_data/write_fruit.csv')