# apply, map 을 활용한 데이터 변환

In [1]:
import pandas as pd

df = pd.DataFrame({'a': [1, 2, 3, 4, 5]})

a가 2보다 작으면 '2 미만', 4보다 작으면 '4 미만', 4보다 크면 '4 이상'이 저장된 b 칼럼 추가

In [3]:
df

   a
0  1
1  2
2  3
3  4
4  5

In [6]:
df['b'] = 0
df

   a  b
0  1  0
1  2  0
2  3  0
3  4  0
4  5  0

In [9]:
a = df[df['a'] < 2]
a

   a  b
0  1  0

In [11]:
df['b'][a.index] = '2 미만'
df

   a     b
0  1  2 미만
1  2     0
2  3     0
3  4     0
4  5     0

In [12]:
b = df[(df['a'] >= 2) & (df['a'] < 4)]
b

   a  b
1  2  0
2  3  0

In [14]:
df['b'][b.index] = '4 미만'
df

<ipython-input-14-d930b722fbac>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'][b.index] = '4 미만'

   a     b
0  1  2 미만
1  2  4 미만
2  3  4 미만
3  4     0
4  5     0

In [17]:
# 위의 warning 나타나지 않게 하기
pd.set_option('mode.chained_assignment', None)

In [18]:
df['b'][b.index] = '4 미만'
df

   a     b
0  1  2 미만
1  2  4 미만
2  3  4 미만
3  4     0
4  5     0

In [21]:
c = df[df['a'] >= 4]
c

   a  b
3  4  0
4  5  0

In [23]:
df['b'][c.index] = '4 이상'
df

   a     b
0  1  2 미만
1  2  4 미만
2  3  4 미만
3  4  4 이상
4  5  4 이상

In [24]:
df['b'][3]

'4 이상'

함수 + apply 를 이용한 해결

In [31]:
def case_function(x):
  if x < 2:
    return '2 미만'
  elif x < 4:
    return '4 미만'
  else:
    return '4 이상'

In [33]:
df['c'] = df['a'].apply(case_function)
df

   a     b     c
0  1  2 미만  2 미만
1  2  4 미만  4 미만
2  3  4 미만  4 미만
3  4  4 이상  4 이상
4  5  4 이상  4 이상

a가 1이면 one, 2이면 two, 3이면 three, 4이면 four, 5이면 five를 출력하는 칼럼 d 생성

사용자 정의함수 사용

In [34]:
def function(x):
  if x == 1:
    return 'one'
  elif x == 2:
    return 'two'
  elif x == 3:
    return 'three'
  elif x == 4:
    return 'four'
  elif x == 5:
    return 'five'

In [35]:
df['d'] = df['a'].apply(function)

In [36]:
df

   a     b     c      d
0  1  2 미만  2 미만    one
1  2  4 미만  4 미만    two
2  3  4 미만  4 미만  three
3  4  4 이상  4 이상   four
4  5  4 이상  4 이상   five

map을 이용한 방법

In [37]:
a = {1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}

In [38]:
df['e'] = df['a'].map(a)
df

   a     b     c      d      e
0  1  2 미만  2 미만    one    one
1  2  4 미만  4 미만    two    two
2  3  4 미만  4 미만  three  three
3  4  4 이상  4 이상   four   four
4  5  4 이상  4 이상   five   five